security:
  providers:
    app_admin_provider:
      entity:
        class: App\Entity\User
        property: username
  encoders:
    App\Entity\User:
      algorithm: auto



  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    admin:
      pattern: ^/
      provider: app_admin_provider
      anonymous: true
      lazy: true
      form_login:
        login_path: login
        check_path: login
      security: true
      guard:
        authenticators:
          - App\Security\AdminAuthenticator
      logout:
        path: logout
        target: mainpage
  role_hierarchy:
    ROLE_ADMIN:       ROLE_ADMIN
    ROLE_SUPER_ADMIN: ROLE_ADMIN
  access_control:
    - { path: ^/(login|logout), roles: IS_AUTHENTICATED_ANONYMOUSLY, host: "admin.%app.root_domain%" }
    - { path: ^/, roles: ROLE_SUPER_ADMIN, host: "admin.%app.root_domain%" }
